apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - observability-bootstrap.yaml
  - grafana.yaml
  - ingress-nginx.yaml
  - loki.yaml
  - alloy.yaml
  - tempo.yaml
  - prometheus.yaml
