apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signoz-demo-data
  namespace: signoz-demo
  labels:
    app.kubernetes.io/name: signoz-demo
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: signoz-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
