apiVersion: v1
kind: Secret
metadata:
  name: signoz-provision-secret
  namespace: signoz
  labels:
    app.kubernetes.io/name: signoz-provision
    app.kubernetes.io/part-of: signoz
type: Opaque
stringData:
  email: "vinikshatriyas@gmail.com"
  password: "Vinay@9380Kumar"
